//go:build go1.22

// Package thunderstormmock provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package thunderstormmock

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AsyncResult Result object for asynchronous scan operations
type AsyncResult struct {
	// Result THOR Report containing findings
	Result *ThorReport `json:"result,omitempty"`

	// Status Current status of the scan
	Status string `json:"status"`
}

// Error Error with message
type Error struct {
	// Message Error message describing the problem
	Message string `json:"message"`
}

// FileObject Wrapped file
type FileObject struct {
	// File File to be checked
	File openapi_types.File `json:"file"`
}

// SampleId Sample ID returned for an asynchronous scan request
type SampleId = int64

// SampleIdObj Object containing the Sample ID returned for an asynchronous scan request
type SampleIdObj struct {
	// Id Sample ID returned for an asynchronous scan request
	Id SampleId `json:"id"`
}

// ThorFinding THOR Finding
type ThorFinding map[string]interface{}

// ThorReport THOR Report containing findings
type ThorReport = []ThorFinding

// ThunderstormInfo Information about the Thunderstorm service instance, including version details, configuration, and license information.
type ThunderstormInfo struct {
	// Arguments Command-line arguments used to start the underlying THOR instance.
	Arguments []string `json:"arguments"`

	// LicenseExpiration Expiration date and time of the license in ISO 8601 format.
	LicenseExpiration time.Time `json:"license_expiration"`

	// LicenseOwner Name of the license owner.
	LicenseOwner string `json:"license_owner"`

	// ScanSpeedLimitation Scan speed limitation in bytes per second. A value of 0 indicates no limitation.
	ScanSpeedLimitation int64 `json:"scan_speed_limitation"`

	// Threads Number of threads used for scanning.
	Threads int64 `json:"threads"`

	// VersionInfo Version information for various components of the Thunderstorm service.
	VersionInfo ThunderstormVersionInfo `json:"version_info"`
}

// ThunderstormStatus Live information about the running THOR instance
type ThunderstormStatus struct {
	// AvgScanTimeMilliseconds Average time in milliseconds to scan a sample
	AvgScanTimeMilliseconds int64 `json:"avg_scan_time_milliseconds"`

	// AvgWaitTimeMilliseconds Average wait time in milliseconds before processing
	AvgWaitTimeMilliseconds int64 `json:"avg_wait_time_milliseconds"`

	// QueuedAsyncRequests Number of asynchronous requests currently in queue
	QueuedAsyncRequests int64 `json:"queued_async_requests"`

	// ScannedSamples Total number of samples that have been scanned
	ScannedSamples int64 `json:"scanned_samples"`
}

// ThunderstormVersionInfo Version information for various components of the Thunderstorm service.
type ThunderstormVersionInfo struct {
	// Build Build timestamp of the THOR scanner.
	Build *string `json:"build,omitempty"`

	// Sigma Version identifier of the Sigma rules.
	Sigma *string `json:"sigma,omitempty"`

	// Signatures Version/timestamp of the signature database.
	Signatures *string `json:"signatures,omitempty"`

	// Thor Version of the THOR scanner engine.
	Thor *string `json:"thor,omitempty"`
}

// TimestampMap Map of timestamps to integer values
type TimestampMap map[string]int64

// AggregationPeriod defines model for AggregationPeriod.
type AggregationPeriod = int64

// HistoryLimit defines model for HistoryLimit.
type HistoryLimit = int64

// SampleSource defines model for SampleSource.
type SampleSource = string

// BadRequest Error with message
type BadRequest = Error

// InternalServerError Error with message
type InternalServerError = Error

// QueueHistory Map of timestamps to integer values
type QueueHistory = TimestampMap

// SampleHistory Map of timestamps to integer values
type SampleHistory = TimestampMap

// CheckParams defines parameters for Check.
type CheckParams struct {
	// Source Specify source for the THOR log
	Source *SampleSource `form:"source,omitempty" json:"source,omitempty"`
}

// CheckAsyncParams defines parameters for CheckAsync.
type CheckAsyncParams struct {
	// Source Specify source for the THOR log
	Source *SampleSource `form:"source,omitempty" json:"source,omitempty"`
}

// GetAsyncResultsParams defines parameters for GetAsyncResults.
type GetAsyncResultsParams struct {
	// Id Sample ID
	Id SampleId `form:"id" json:"id"`
}

// QueueHistoryParams defines parameters for QueueHistory.
type QueueHistoryParams struct {
	// Aggregate Aggregate this many minutes per value (default 1).
	Aggregate *AggregationPeriod `form:"aggregate,omitempty" json:"aggregate,omitempty"`

	// Limit Give a history for the last this many minutes (default infinite).
	Limit *HistoryLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// SampleHistoryParams defines parameters for SampleHistory.
type SampleHistoryParams struct {
	// Aggregate Aggregate this many minutes per value (default 1).
	Aggregate *AggregationPeriod `form:"aggregate,omitempty" json:"aggregate,omitempty"`

	// Limit Give a history for the last this many minutes (default infinite).
	Limit *HistoryLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CheckMultipartRequestBody defines body for Check for multipart/form-data ContentType.
type CheckMultipartRequestBody = FileObject

// CheckAsyncMultipartRequestBody defines body for CheckAsync for multipart/form-data ContentType.
type CheckAsyncMultipartRequestBody = FileObject

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check a file with THOR
	// (POST /check)
	Check(w http.ResponseWriter, r *http.Request, params CheckParams)
	// Check a file with THOR asynchronously
	// (POST /checkAsync)
	CheckAsync(w http.ResponseWriter, r *http.Request, params CheckAsyncParams)
	// Retrieve the results of an asynchronous file check
	// (GET /getAsyncResults)
	GetAsyncResults(w http.ResponseWriter, r *http.Request, params GetAsyncResultsParams)
	// Receive static information about the running THOR instance
	// (GET /info)
	Info(w http.ResponseWriter, r *http.Request)
	// Retrieve a history of how many asynchronous requests were queued
	// (GET /queueHistory)
	QueueHistory(w http.ResponseWriter, r *http.Request, params QueueHistoryParams)
	// Retrieve a history of how many samples were scanned
	// (GET /sampleHistory)
	SampleHistory(w http.ResponseWriter, r *http.Request, params SampleHistoryParams)
	// Receive live information about the running THOR instance
	// (GET /status)
	Status(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Check operation middleware
func (siw *ServerInterfaceWrapper) Check(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckParams

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Check(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckAsync operation middleware
func (siw *ServerInterfaceWrapper) CheckAsync(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckAsyncParams

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckAsync(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsyncResults operation middleware
func (siw *ServerInterfaceWrapper) GetAsyncResults(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAsyncResultsParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsyncResults(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Info operation middleware
func (siw *ServerInterfaceWrapper) Info(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Info(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueueHistory operation middleware
func (siw *ServerInterfaceWrapper) QueueHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params QueueHistoryParams

	// ------------- Optional query parameter "aggregate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "aggregate", r.URL.Query(), &params.Aggregate, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "aggregate", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueueHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SampleHistory operation middleware
func (siw *ServerInterfaceWrapper) SampleHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SampleHistoryParams

	// ------------- Optional query parameter "aggregate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "aggregate", r.URL.Query(), &params.Aggregate, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "aggregate", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SampleHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Status operation middleware
func (siw *ServerInterfaceWrapper) Status(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Status(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/check", wrapper.Check)
	m.HandleFunc("POST "+options.BaseURL+"/checkAsync", wrapper.CheckAsync)
	m.HandleFunc("GET "+options.BaseURL+"/getAsyncResults", wrapper.GetAsyncResults)
	m.HandleFunc("GET "+options.BaseURL+"/info", wrapper.Info)
	m.HandleFunc("GET "+options.BaseURL+"/queueHistory", wrapper.QueueHistory)
	m.HandleFunc("GET "+options.BaseURL+"/sampleHistory", wrapper.SampleHistory)
	m.HandleFunc("GET "+options.BaseURL+"/status", wrapper.Status)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xae5PbOHL/KjgkW9l1KAkkRYrSVf6Y9XrPc36Mb2Z8m43jUiCyKWGHBGkAlEfnmu+e",
	"AkBKFEnNw/vIw+WySwTQ3ejnDw18wXGRlwUHriRefMElFTQHBcL8OluvBaypYgV/B4IVif6YgIwFK/VH",
	"vNhPAaQ2TKKc8h3KGa8USFSCQFuaVYC+TSClVaaQ+90YO5jplZ8qEDvsYE5zwAtMG0LYwTLeQE41s7QQ",
	"OVV4gRlX4RQ7WO1KsD9hDQLf3Tn4JZOqELvXLGeqL+Bf2BYQRRs7CaWFQGoDKKNSDYi8F5TxlHGm4KS8",
	"mWH3VFmvaF5mcFVUIoa+rFclxCzdIWnG97Jev7y4RFmxPiGJnX0kSs1ZKsH4Gt9pzgI+VSDV90XCwBj3",
	"R5bB+zIrqLFqXHAF3OgvrzLFSirURO9olFBlaB6o/7OAFC/wP00OvjOxo3KiqV6sfoFYWbbHG3zTkNZ7",
	"y5EmjTRnyjjja0RRyjK9Ey0sE5DghRIVWPFlWXBpRf+eJpd2Ox3RaVlmLDYOO/lFapaPlfuFEIUYEvmc",
	"b2nGEnSIDLRmW+D4zsHnXIHgNLsCsQVhSfzuAr3ntFKbQrB/QKKF+FsFFdQx8Jtxv2Y5SEXz8g0th4Q4",
	"Q3+9uniL3tASfWZqg4DGG6RYDiinZQkJUoVx3U9aOJQBX6sN+hakYjlVkHyHUlHkrUA0K4Fr6s1iaj+P",
	"8T5s/uhNXoKqBJeIPnKz0kgpkYwp19t49B5NaqilMnlX7nh8CbLKBhKa/Y4KE2QmR1A9fSMKXlSWOSpK",
	"EEYjEjsYbo1cmpKoaX6oNXir8IJXWebgrFgvtyCk5bH1x2RMsINzkJKudS65qmTJYqZZ6CBFaVHxxMyw",
	"6WFTSFUnJNeb6eVjFzs4gy1keIF/okKHuF5QJJWWBr+8vn5nI8fkLsqXLNGMRp/Y38+LWZp7P9+MTB5l",
	"hqxHvHBE3JE7v3bDBYkW3mwckfk08udB8K/EXRCCTaagsuDLuKi0f7jNB2l2nVMVb3Re+fAF28SG/+Xj",
	"v/3pTx8+/vkOOzhlkGkZJo1/ObhIUwkKL/woDO4+OliyNaeqEjZ963plJAtGxB95c9z1oR9AQawkKlZp",
	"JWPt++ivdEuvzBQUF4lOdzeMa64/n12eocvKZMBCsLVJ9qzOMTorVhksax1ffP/j+6vnRnGFliUMHKzo",
	"Wu/SjuGP2qeqPKc6YixtTQDtV9ZFwqoHm71ZWrO5XmmT+HGsQQa5hQoH/W2pQEty21KVN/M1NRv1eBH4",
	"4XzPTZZUSDCZXxsLbpnU5PAOrKsq4LUPGnMIqZarnbJpn8qYMW2dZ+iDgM+CKVhiB2/gVtsg9SihEFGg",
	"if53RTxCaLCaeWEwm828cD6bhkGQaq4bKjeWZJ4EeIHTNJ5Nk4CmseclburGsyhI55EbTON4tqKmtm6o",
	"ixd4HhKfTiMSBl4UzKIwCpM4SIm3ikgQh9OpO1358dxd2RVeEOIFTqibeP4sSlc0TqNpQuaJG9H5NIE0",
	"8uPEX6UxCSGaw2zqzVfUTyCYxck8pATIlEYzLXFO1yxebvTehK4Bb1+9vfjpLXZwSbWKcTgjZBZEK3ea",
	"QkRjd7WKV6vUT8LAC10/ifRMEDmT0iSFOugl+wd07GMK8N3+p4EeKeOJwRHaRRRVlTaYTcmIcprtJJNI",
	"59cMlFlcCp2AVA00xD6R3ZuMN4W4hLIQSlNo2HST3/NKCOAK2XFUpDbxxpS3E10zLduhFWhgUWfkg9Pv",
	"kVEba3xo2H7czytqKOPgfXU/Fsh8tmWhyZXd/e9z6PDaehjZsZUWV++pFMUqg/xBkRvqQzK3wFiP+U/C",
	"1q4acR2LbD72lmhyum6tAMUbiG+MQveod8U4NbD0fnkN6SFhrUOdD5wxalc7/wEJU5G11Lrs8YHKV8Pc",
	"tje4nj8NnIfh+UGEi9UvfSmsIttwVZvpV8r2BeuaZyTsxQ1LHoqZvcq6SmbJoIp1jP1YB7POp0nC9OZo",
	"9q7FWCPubhUzaaBZeYJwHbw9vZm1drCtvDqpHAGUr4Alb2j2K1DJWQZCPQ6T3PxtG+xenr9/eTPyBjBJ",
	"eO36Cz9Y+NOx67q+7868U5DEix7EJN88k8+ePb988cOLt9fnZ6+fPbsfm8zdaBqRO6e9HqF3Wm9SofrP",
	"An1Dols0Qt9U+h/5EMk5CcJjks+e/XDx5uz87asXPz8oUUDCKLoHL/kjEoxc7yReuipyUBvrbo+FR5CC",
	"AK4P1h/2RzN0CRKoiDc6INoASjNYamrLt/rDHvxELSD14t9fYAe/fHX9uoOmZJED2kOqPpZyBq16U22y",
	"Zb7MJE2qvFyuQb2XIOQZT65o/gp26M/opsr0FAFrJpXYLS9hfVECfwW7F7fo6uwNOouNF0n0LbnV9vzu",
	"fju4LiHBtO0afSGeF3lZKRBajp28qeXozqqHXl08wJDM5zNyj+XdcES8EQketjwq1MbE4dfYX1NBhy8d",
	"459xQ3vQ/uRg/2uXBPMlIW7H/PXyE8Y/AOn59ClA+j8rQnz4Lx6LXanGSZa11BoFoeuSNqp2/cBz595X",
	"AOsx3MJpcP3mP/aQWkPiOSGE+MT+mdr/0jRN9f+ryP4egtQzN4yiuRfO/WQ2c0PPI8k8iiI/TdMkmkbx",
	"AVJPPRon81UQTMGNo6lP52nk+nPieasgJAmQVTqNwshrQ+owJNNwGk9nfjydzaJpEkUeSXzwwigmiet7",
	"Mxp7XgwEQjJLYj+AKIhCL4oDPyXhIKS2sV7DaR3fup7UqjoJnbtGeAg9MwW5fAwSbmrtgRYVgu5sra14",
	"AkKqQuTnPC36FVd/1ViHFRzRVVEp20VsrUMSxJbFgBiXivIYHMR4nFWaJ6rrLUpAUZZJR1ftlK0r21Fw",
	"EOUJylgMXOr1e1bjY1xDxbpqXByPRpYGdvCkKNWEw60SBZ+olkwTO2USV1IV+UhtCjHe5ZkO3ZrbEm5L",
	"ZqXYl97ZiETXhCzMX+26zdziMzd2pUnOeFPMZQmQLE3rtiajo30jgCYSL9zQwfXml6zW7KpiJtU1hZ7M",
	"EJkuiLfwNY6QbJ3r0BWmA+B6BgpEo3WYBJE7C6eAW2lQ1mQmxJ243sgNSRBoMKN3qvEJGUdjYqDcMQ5s",
	"abJ3HCrynPJklDEOaD8PVdI2mKSiwhrfqDnbafMap2zsfmS0X22nvXt3jgB9Jx6yaO94tB/TWQ2M35km",
	"Wn3qO/ggOr+6QFFIXGS98WhXpxxlfx7QxEcGzzl9wTvu1JVR146uPGbqsQiNE/bIn/DK3glIHx/MNHSY",
	"pjdu0re5aJEQFzwZo7P6yqVIEUE6i8RUT+FFa+WRcORRR6N9kPQ0UOUrEFYHZor1Pn0IMqduxtdH7HSQ",
	"PYJfNw7vT5gH7/y7XWcSY/dUdETTacXVoD92bX/KWAfdDB+5DrJdnWhqvGbbo0zaStqiMho8DtpOot2u",
	"l0Yy7cLLnGUZs74g8cJzHTP+mTI1NE4cbDr0ydKcVpf1CdWO1E2TZd3Wxgs3CqPQJ/2T6n0i9C4MtyDo",
	"GmwkM47as03O0q5O6156e6d6L49wnPu2e0oWPX9YoBWkhTDNmBiktMeRJ0bOCQWfjqOjxkGzAMX7lhbj",
	"9lrl6aL0LNo7qxeKZojvRWluNMxNxYZuAa0AeKuddgjr2jecR12DHvXcOkKd0phzn5vda/eH4rKdM3oq",
	"qQeP4lMnty0Vpu1wyEdNHRgCWuNei60GFl123+vPxhfNzdSepo5/qykxVN26wKRfaCxSObm7BLhiKWsy",
	"OaArvcCccOQxw/uwzhDbPfg5wXvS2+x+kTnNrKiE/pZ7IKqHODZD7dpmvwNqRcDXjHdY1aBsqKnZd6n2",
	"deLJ9tqXxwRq59acWtU09E2erGfbat+55mt8wnMRCRfTwOSH9sfZghC8mLth0P3uBngxnRPP7w74BC9C",
	"N4x6KzT5YDr3vb5OtJrYYFRdb5hEZ+/OEc2y4rNEu6IyyR+47UibLRrrNCVBbSA3ELAUxZYlIJ9SMcem",
	"Y6ey/aHsKEbP3p3jPeLQRjddxjsHFyVwWupTsT8m42l9PjRGnJgOuHkyU8iBrudzPVw/aLDXA5ovNjQt",
	"wDhPmmmG7uHdzYdhtHOYMjl6RaLPlYfHHbtTYOno/cek9fij+7jC067xW92wty517rtfz5hU2sX3TeE7",
	"B0+tHMN7qeWdtF6C3Dk4eMySoUcbd0ftnZO2a/pC5r7po15k3cDc1z/VF47qfLYbdg1L+f+tf7QvXO51",
	"kJyW3ZsX2dy8/G90lr5xB3xnDar10sModw2DLz6UYLAFm9/sZAMUO5dMRgTjkOOeN/2lw6vnUieu3E68",
	"OWNJ75WW80Sb4zvrmb+Ta7Xf0Dz8tscYTqs3Pr5gpjxxEEtRLccqA6dthf9Z13u6X7T8sNmBdcWmSp/w",
	"vxj0EVXrhMVPrbvHfnhuz96/Y8XpdEeHXiE2D7ksdtIQo5G+BgEOElRBq2PioPF4/Jua7mtV2jKhMZq1",
	"36fOI8D788jhOWyRok3x2b6BHT53fgZRP+NLesY8enr41CLVf1x85zy46Oit76n8cb9xjoT+mvgdjsGv",
	"1+mAOWX3vePX2LM5vBtu9Sm7H5DHTyv/rxjxWOrf24pDmjxhuH2L795Mmj2x4zdgNsvoD8qkNbfH5VJ7",
	"XNOHVWf/FLbWoHNotck6pQ6mxezpHdGuMTRdk36H4M3rIqZZj0QlMrzAG6XKxWSS6SmbQqpFRCIyoSWb",
	"bF3jrTWn3nUFT8qCcXXQgT3Itg8QzYt9jQHNnfxpCqJxyXZh7z4pkgeaB0TyOLJP024D+0xF/Xj33wEA",
	"AP//D9ekAzcyAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
