// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package main

import (
	"log"
	"net/http"

	thunderstormmock "github.com/NextronSystems/thunderstorm-mock/go"
)

func main() {
	log.Printf("Server started")

	InfoAPIService := thunderstormmock.NewInfoAPIService()
	InfoAPIController := thunderstormmock.NewInfoAPIController(InfoAPIService)

	ResultsAPIService := thunderstormmock.NewResultsAPIService()
	ResultsAPIController := thunderstormmock.NewResultsAPIController(ResultsAPIService)

	ScanAPIService := thunderstormmock.NewScanAPIService()
	ScanAPIController := thunderstormmock.NewScanAPIController(ScanAPIService)

	router := thunderstormmock.NewRouter(InfoAPIController, ResultsAPIController, ScanAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
