generatorName: go-server
inputSpec: https://github.com/NextronSystems/thunderstorm-openapi/releases/download/v1.0.0/openapi.yaml
enablePostProcessFile: true
generateAliasAsModel: true
gitUserId: NextronSystems
gitRepoId: thunderstorm-mock
globalProperties:
  skipFormModel: false
additionalProperties:
  packageName: thunderstormmock
  packageVersion: 1.0.0
