// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

import (
	"context"
	"net/http"
	"os"
)

// InfoAPIRouter defines the required methods for binding the api requests to a responses for the InfoAPI
// The InfoAPIRouter implementation should parse necessary information from the http request,
// pass the data to a InfoAPIServicer to perform the required actions, then write the service results to the http response.
type InfoAPIRouter interface {
	QueueHistory(http.ResponseWriter, *http.Request)
	SampleHistory(http.ResponseWriter, *http.Request)
	Info(http.ResponseWriter, *http.Request)
	Status(http.ResponseWriter, *http.Request)
}

// ResultsAPIRouter defines the required methods for binding the api requests to a responses for the ResultsAPI
// The ResultsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ResultsAPIServicer to perform the required actions, then write the service results to the http response.
type ResultsAPIRouter interface {
	GetAsyncResults(http.ResponseWriter, *http.Request)
}

// ScanAPIRouter defines the required methods for binding the api requests to a responses for the ScanAPI
// The ScanAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ScanAPIServicer to perform the required actions, then write the service results to the http response.
type ScanAPIRouter interface {
	Check(http.ResponseWriter, *http.Request)
	CheckAsync(http.ResponseWriter, *http.Request)
}

// InfoAPIServicer defines the api actions for the InfoAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type InfoAPIServicer interface {
	QueueHistory(context.Context, int64, int64) (ImplResponse, error)
	SampleHistory(context.Context, int64, int64) (ImplResponse, error)
	Info(context.Context) (ImplResponse, error)
	Status(context.Context) (ImplResponse, error)
}

// ResultsAPIServicer defines the api actions for the ResultsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ResultsAPIServicer interface {
	GetAsyncResults(context.Context, int64) (ImplResponse, error)
}

// ScanAPIServicer defines the api actions for the ScanAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ScanAPIServicer interface {
	Check(context.Context, *os.File, string) (ImplResponse, error)
	CheckAsync(context.Context, *os.File, string) (ImplResponse, error)
}
