// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

import (
	"context"
)

// InfoAPIService is a service that implements the logic for the InfoAPIServicer
// This service should implement the business logic for every endpoint for the InfoAPI API.
// Include any external packages or services that will be required by this service.
type InfoAPIService struct {
}

// NewInfoAPIService creates a default api service
func NewInfoAPIService() *InfoAPIService {
	return &InfoAPIService{}
}

// QueueHistory - Retrieve a history of how many asynchronous requests were queued
func (s *InfoAPIService) QueueHistory(ctx context.Context, aggregate int64, limit int64) (ImplResponse, error) {
	return Response(200, History(queueHistory, aggregate, limit)), nil
}

// SampleHistory - Retrieve a history of how many samples were scanned
func (s *InfoAPIService) SampleHistory(ctx context.Context, aggregate int64, limit int64) (ImplResponse, error) {
	return Response(200, History(sampleHistory, aggregate, limit)), nil
}

// Info - Receive static information about the running THOR instance
func (s *InfoAPIService) Info(ctx context.Context) (ImplResponse, error) {
	return Response(200, MockInfo()), nil
}

// Status - Receive live information about the running THOR instance
func (s *InfoAPIService) Status(ctx context.Context) (ImplResponse, error) {
	return Response(200, MockStatus()), nil
}
