// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

import (
	"net/http"
	"os"
	"strings"
)

// ScanAPIController binds http requests to an api service and writes the service results to the http response
type ScanAPIController struct {
	service      ScanAPIServicer
	errorHandler ErrorHandler
}

// ScanAPIOption for how the controller is set up.
type ScanAPIOption func(*ScanAPIController)

// WithScanAPIErrorHandler inject ErrorHandler into controller
func WithScanAPIErrorHandler(h ErrorHandler) ScanAPIOption {
	return func(c *ScanAPIController) {
		c.errorHandler = h
	}
}

// NewScanAPIController creates a default api controller
func NewScanAPIController(s ScanAPIServicer, opts ...ScanAPIOption) *ScanAPIController {
	controller := &ScanAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ScanAPIController
func (c *ScanAPIController) Routes() Routes {
	return Routes{
		"Check": Route{
			"Check",
			strings.ToUpper("Post"),
			"/api/v1/check",
			c.Check,
		},
		"CheckAsync": Route{
			"CheckAsync",
			strings.ToUpper("Post"),
			"/api/v1/checkAsync",
			c.CheckAsync,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the ScanAPIController
func (c *ScanAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"Check",
			strings.ToUpper("Post"),
			"/api/v1/check",
			c.Check,
		},
		Route{
			"CheckAsync",
			strings.ToUpper("Post"),
			"/api/v1/checkAsync",
			c.CheckAsync,
		},
	}
}

// Check - Check a file with THOR
func (c *ScanAPIController) Check(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseMultipartForm(32 << 20); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var fileParam *os.File
	{
		param, err := ReadFormFileToTempFile(r, "file")
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "file", Err: err}, nil)
			return
		}

		fileParam = param
	}

	var sourceParam string
	if query.Has("source") {
		param := query.Get("source")

		sourceParam = param
	} else {
	}
	result, err := c.service.Check(r.Context(), fileParam, sourceParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// CheckAsync - Check a file with THOR asynchronously
func (c *ScanAPIController) CheckAsync(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseMultipartForm(32 << 20); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var fileParam *os.File
	{
		param, err := ReadFormFileToTempFile(r, "file")
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "file", Err: err}, nil)
			return
		}

		fileParam = param
	}

	var sourceParam string
	if query.Has("source") {
		param := query.Get("source")

		sourceParam = param
	} else {
	}
	result, err := c.service.CheckAsync(r.Context(), fileParam, sourceParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
