// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

import (
	"context"
	"errors"
	"net/http"
	"os"
)

// ScanAPIService is a service that implements the logic for the ScanAPIServicer
// This service should implement the business logic for every endpoint for the ScanAPI API.
// Include any external packages or services that will be required by this service.
type ScanAPIService struct {
}

// NewScanAPIService creates a default api service
func NewScanAPIService() *ScanAPIService {
	return &ScanAPIService{}
}

// Check - Check a file with THOR
func (s *ScanAPIService) Check(ctx context.Context, file *os.File, source string) (ImplResponse, error) {
	// TODO - update Check with the required logic for this service method.
	// Add api_scan_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ThorReport{}) or use other options such as http.Ok ...
	// return Response(200, ThorReport{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Check method not implemented")
}

// CheckAsync - Check a file with THOR asynchronously
func (s *ScanAPIService) CheckAsync(ctx context.Context, file *os.File, source string) (ImplResponse, error) {
	// TODO - update CheckAsync with the required logic for this service method.
	// Add api_scan_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, SampleIdObj{}) or use other options such as http.Ok ...
	// return Response(200, SampleIdObj{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CheckAsync method not implemented")
}
