// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

import (
	"context"
	"fmt"
	"os"
)

// ScanAPIService is a service that implements the logic for the ScanAPIServicer
// This service should implement the business logic for every endpoint for the ScanAPI API.
// Include any external packages or services that will be required by this service.
type ScanAPIService struct {
}

// NewScanAPIService creates a default api service
func NewScanAPIService() *ScanAPIService {
	return &ScanAPIService{}
}

// Check - Check a file with THOR
func (s *ScanAPIService) Check(ctx context.Context, file *os.File, source string) (ImplResponse, error) {
	if resp, found := getSpecialTriggerResponse(source); found {
		return resp, nil
	}

	req, err := StoreScanRequest(true, file, source)
	if err != nil {
		return Response(500, Error{Message: fmt.Sprintf("Internal server error: %v", err)}), nil
	}
	return Response(200, req.ToThorReport()), nil
}

// CheckAsync - Check a file with THOR asynchronously
func (s *ScanAPIService) CheckAsync(ctx context.Context, file *os.File, source string) (ImplResponse, error) {
	if resp, found := getSpecialTriggerResponse(source); found {
		return resp, nil
	}

	req, err := StoreScanRequest(false, file, source)
	if err != nil {
		return Response(500, Error{Message: fmt.Sprintf("Internal server error: %v", err)}), nil
	}
	return Response(200, SampleId{Id: int64(req.ID)}), nil
}

// getSpecialTriggerResponse checks source for special testing-related triggers
// and returns a corresponding response and true if found, else returns false.
func getSpecialTriggerResponse(source string) (ImplResponse, bool) {
	switch source {
	case "error 400":
		return Response(400, Error{Message: "Invalid parameters given"}), true
	case "error 500":
		return Response(500, Error{Message: "Internal server error"}), true
	}
	return ImplResponse{}, false
}
