// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

import (
	"net/http"
	"strings"
)

// InfoAPIController binds http requests to an api service and writes the service results to the http response
type InfoAPIController struct {
	service      InfoAPIServicer
	errorHandler ErrorHandler
}

// InfoAPIOption for how the controller is set up.
type InfoAPIOption func(*InfoAPIController)

// WithInfoAPIErrorHandler inject ErrorHandler into controller
func WithInfoAPIErrorHandler(h ErrorHandler) InfoAPIOption {
	return func(c *InfoAPIController) {
		c.errorHandler = h
	}
}

// NewInfoAPIController creates a default api controller
func NewInfoAPIController(s InfoAPIServicer, opts ...InfoAPIOption) *InfoAPIController {
	controller := &InfoAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the InfoAPIController
func (c *InfoAPIController) Routes() Routes {
	return Routes{
		"QueueHistory": Route{
			"QueueHistory",
			strings.ToUpper("Get"),
			"/api/v1/queueHistory",
			c.QueueHistory,
		},
		"SampleHistory": Route{
			"SampleHistory",
			strings.ToUpper("Get"),
			"/api/v1/sampleHistory",
			c.SampleHistory,
		},
		"Info": Route{
			"Info",
			strings.ToUpper("Get"),
			"/api/v1/info",
			c.Info,
		},
		"Status": Route{
			"Status",
			strings.ToUpper("Get"),
			"/api/v1/status",
			c.Status,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the InfoAPIController
func (c *InfoAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"QueueHistory",
			strings.ToUpper("Get"),
			"/api/v1/queueHistory",
			c.QueueHistory,
		},
		Route{
			"SampleHistory",
			strings.ToUpper("Get"),
			"/api/v1/sampleHistory",
			c.SampleHistory,
		},
		Route{
			"Info",
			strings.ToUpper("Get"),
			"/api/v1/info",
			c.Info,
		},
		Route{
			"Status",
			strings.ToUpper("Get"),
			"/api/v1/status",
			c.Status,
		},
	}
}

// QueueHistory - Retrieve a history of how many asynchronous requests were queued
func (c *InfoAPIController) QueueHistory(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var aggregateParam int64
	if query.Has("aggregate") {
		param, err := parseNumericParameter[int64](
			query.Get("aggregate"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "aggregate", Err: err}, nil)
			return
		}

		aggregateParam = param
	} else {
	}
	var limitParam int64
	if query.Has("limit") {
		param, err := parseNumericParameter[int64](
			query.Get("limit"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "limit", Err: err}, nil)
			return
		}

		limitParam = param
	} else {
	}
	result, err := c.service.QueueHistory(r.Context(), aggregateParam, limitParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// SampleHistory - Retrieve a history of how many samples were scanned
func (c *InfoAPIController) SampleHistory(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var aggregateParam int64
	if query.Has("aggregate") {
		param, err := parseNumericParameter[int64](
			query.Get("aggregate"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "aggregate", Err: err}, nil)
			return
		}

		aggregateParam = param
	} else {
	}
	var limitParam int64
	if query.Has("limit") {
		param, err := parseNumericParameter[int64](
			query.Get("limit"),
			WithParse[int64](parseInt64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "limit", Err: err}, nil)
			return
		}

		limitParam = param
	} else {
	}
	result, err := c.service.SampleHistory(r.Context(), aggregateParam, limitParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// Info - Receive static information about the running THOR instance
func (c *InfoAPIController) Info(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.Info(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// Status - Receive live information about the running THOR instance
func (c *InfoAPIController) Status(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.Status(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
