// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

import (
	"context"
	"errors"
	"net/http"
)

// InfoAPIService is a service that implements the logic for the InfoAPIServicer
// This service should implement the business logic for every endpoint for the InfoAPI API.
// Include any external packages or services that will be required by this service.
type InfoAPIService struct {
}

// NewInfoAPIService creates a default api service
func NewInfoAPIService() *InfoAPIService {
	return &InfoAPIService{}
}

// QueueHistory - Retrieve a history of how many asynchronous requests were queued
func (s *InfoAPIService) QueueHistory(ctx context.Context, aggregate int64, limit int64) (ImplResponse, error) {
	// TODO - update QueueHistory with the required logic for this service method.
	// Add api_info_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TimestampMap{}) or use other options such as http.Ok ...
	// return Response(200, TimestampMap{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("QueueHistory method not implemented")
}

// SampleHistory - Retrieve a history of how many samples were scanned
func (s *InfoAPIService) SampleHistory(ctx context.Context, aggregate int64, limit int64) (ImplResponse, error) {
	// TODO - update SampleHistory with the required logic for this service method.
	// Add api_info_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TimestampMap{}) or use other options such as http.Ok ...
	// return Response(200, TimestampMap{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SampleHistory method not implemented")
}

// Info - Receive static information about the running THOR instance
func (s *InfoAPIService) Info(ctx context.Context) (ImplResponse, error) {
	// TODO - update Info with the required logic for this service method.
	// Add api_info_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ThunderstormInfo{}) or use other options such as http.Ok ...
	// return Response(200, ThunderstormInfo{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Info method not implemented")
}

// Status - Receive live information about the running THOR instance
func (s *InfoAPIService) Status(ctx context.Context) (ImplResponse, error) {
	// TODO - update Status with the required logic for this service method.
	// Add api_info_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ThunderstormStatus{}) or use other options such as http.Ok ...
	// return Response(200, ThunderstormStatus{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Status method not implemented")
}
