// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

// ImplResponse defines an implementation response with error code and the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
