// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

// TimestampMap - Map of timestamps to integer values
type TimestampMap struct {
}

// AssertTimestampMapRequired checks if the required fields are not zero-ed
func AssertTimestampMapRequired(obj TimestampMap) error {
	return nil
}

// AssertTimestampMapConstraints checks if the values respects the defined constraints
func AssertTimestampMapConstraints(obj TimestampMap) error {
	return nil
}
