// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

// ThorReport - THOR Report containing findings
type ThorReport struct {
	Items []ThorFinding
}

// AssertThorReportRequired checks if the required fields are not zero-ed
func AssertThorReportRequired(obj ThorReport) error {
	return nil
}

// AssertThorReportConstraints checks if the values respects the defined constraints
func AssertThorReportConstraints(obj ThorReport) error {
	return nil
}
