// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

import (
	"os"
)

// FileObject - Wrapped file
type FileObject struct {

	// File to be checked
	File *os.File `json:"file"`
}

// AssertFileObjectRequired checks if the required fields are not zero-ed
func AssertFileObjectRequired(obj FileObject) error {
	elements := map[string]interface{}{
		"file": obj.File,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertFileObjectConstraints checks if the values respects the defined constraints
func AssertFileObjectConstraints(obj FileObject) error {
	return nil
}
