// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

// ThorFinding - THOR Finding
type ThorFinding struct {
}

// AssertThorFindingRequired checks if the required fields are not zero-ed
func AssertThorFindingRequired(obj ThorFinding) error {
	return nil
}

// AssertThorFindingConstraints checks if the values respects the defined constraints
func AssertThorFindingConstraints(obj ThorFinding) error {
	return nil
}
