// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

// ThunderstormStatus - Live information about the running THOR instance
type ThunderstormStatus struct {

	// Total number of samples that have been scanned
	ScannedSamples int64 `json:"scanned_samples"`

	// Number of asynchronous requests currently in queue
	QueuedAsyncRequests int64 `json:"queued_async_requests"`

	// Average time in milliseconds to scan a sample
	AvgScanTimeMilliseconds int64 `json:"avg_scan_time_milliseconds"`

	// Average wait time in milliseconds before processing
	AvgWaitTimeMilliseconds int64 `json:"avg_wait_time_milliseconds"`
}

// AssertThunderstormStatusRequired checks if the required fields are not zero-ed
func AssertThunderstormStatusRequired(obj ThunderstormStatus) error {
	elements := map[string]interface{}{
		"scanned_samples":            obj.ScannedSamples,
		"queued_async_requests":      obj.QueuedAsyncRequests,
		"avg_scan_time_milliseconds": obj.AvgScanTimeMilliseconds,
		"avg_wait_time_milliseconds": obj.AvgWaitTimeMilliseconds,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertThunderstormStatusConstraints checks if the values respects the defined constraints
func AssertThunderstormStatusConstraints(obj ThunderstormStatus) error {
	return nil
}
