// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

import (
	"time"
)

// ThunderstormInfo - Information about the Thunderstorm service instance, including version details, configuration, and license information.
type ThunderstormInfo struct {
	VersionInfo ThunderstormVersionInfo `json:"version_info"`

	// Command-line arguments used to start the underlying THOR instance.
	Arguments []string `json:"arguments"`

	// Expiration date and time of the license in ISO 8601 format.
	LicenseExpiration time.Time `json:"license_expiration"`

	// Name of the license owner.
	LicenseOwner string `json:"license_owner"`

	// Scan speed limitation in bytes per second. A value of 0 indicates no limitation.
	ScanSpeedLimitation int64 `json:"scan_speed_limitation"`

	// Number of threads used for scanning.
	Threads int64 `json:"threads"`
}

// AssertThunderstormInfoRequired checks if the required fields are not zero-ed
func AssertThunderstormInfoRequired(obj ThunderstormInfo) error {
	elements := map[string]interface{}{
		"version_info":          obj.VersionInfo,
		"arguments":             obj.Arguments,
		"license_expiration":    obj.LicenseExpiration,
		"license_owner":         obj.LicenseOwner,
		"scan_speed_limitation": obj.ScanSpeedLimitation,
		"threads":               obj.Threads,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertThunderstormVersionInfoRequired(obj.VersionInfo); err != nil {
		return err
	}
	return nil
}

// AssertThunderstormInfoConstraints checks if the values respects the defined constraints
func AssertThunderstormInfoConstraints(obj ThunderstormInfo) error {
	if err := AssertThunderstormVersionInfoConstraints(obj.VersionInfo); err != nil {
		return err
	}
	return nil
}
