// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

// ThunderstormVersionInfo - Version information for various components of the Thunderstorm service.
type ThunderstormVersionInfo struct {

	// Version of the THOR scanner engine.
	Thor string `json:"thor,omitempty"`

	// Build timestamp of the THOR scanner.
	Build string `json:"build,omitempty"`

	// Version/timestamp of the signature database.
	Signatures string `json:"signatures,omitempty"`

	// Version identifier of the Sigma rules.
	Sigma string `json:"sigma,omitempty"`
}

// AssertThunderstormVersionInfoRequired checks if the required fields are not zero-ed
func AssertThunderstormVersionInfoRequired(obj ThunderstormVersionInfo) error {
	return nil
}

// AssertThunderstormVersionInfoConstraints checks if the values respects the defined constraints
func AssertThunderstormVersionInfoConstraints(obj ThunderstormVersionInfo) error {
	return nil
}
