// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

// SampleIdObj - Object containing the Sample ID returned for an asynchronous scan request
type SampleIdObj struct {

	// Sample ID returned for an asynchronous scan request
	Id int64 `json:"id"`
}

// AssertSampleIdObjRequired checks if the required fields are not zero-ed
func AssertSampleIdObjRequired(obj SampleIdObj) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSampleIdObjConstraints checks if the values respects the defined constraints
func AssertSampleIdObjConstraints(obj SampleIdObj) error {
	return nil
}
