// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * THOR Thunderstorm API
 *
 * This API allows you to send files to THOR to scan them and provides information about the running THOR instance.
 *
 * API version: 1.0.0
 */

package thunderstormmock

// SampleId - Sample ID returned for an asynchronous scan request
type SampleId struct {

	// Sample ID
	Id int64 `json:"id"`
}

// AssertSampleIdRequired checks if the required fields are not zero-ed
func AssertSampleIdRequired(obj SampleId) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSampleIdConstraints checks if the values respects the defined constraints
func AssertSampleIdConstraints(obj SampleId) error {
	return nil
}
