//go:build go1.22

// Package thunderstormmock provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package thunderstormmock

import (
	"context"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AsyncResult Result object for asynchronous scan operations
type AsyncResult struct {
	// Result THOR Report containing findings
	Result *ThorReport `json:"result,omitempty"`

	// Status Current status of the scan
	Status string `json:"status"`
}

// Error Error with message
type Error struct {
	// Message Error message describing the problem
	Message string `json:"message"`
}

// FileObject Wrapped file
type FileObject struct {
	// File File to be checked
	File openapi_types.File `json:"file"`
}

// SampleId Sample ID returned for an asynchronous scan request
type SampleId = int64

// SampleIdObj Object containing the Sample ID returned for an asynchronous scan request
type SampleIdObj struct {
	// Id Sample ID returned for an asynchronous scan request
	Id SampleId `json:"id"`
}

// ThorFinding THOR Finding
type ThorFinding map[string]interface{}

// ThorReport THOR Report containing findings
type ThorReport = []ThorFinding

// ThunderstormInfo Information about the Thunderstorm service instance, including version details, configuration, and license information.
type ThunderstormInfo struct {
	// Arguments Command-line arguments used to start the underlying THOR instance.
	Arguments []string `json:"arguments"`

	// LicenseExpiration Expiration date and time of the license in ISO 8601 format.
	LicenseExpiration time.Time `json:"license_expiration"`

	// LicenseOwner Name of the license owner.
	LicenseOwner string `json:"license_owner"`

	// ScanSpeedLimitation Scan speed limitation in bytes per second. A value of 0 indicates no limitation.
	ScanSpeedLimitation int64 `json:"scan_speed_limitation"`

	// Threads Number of threads used for scanning.
	Threads int64 `json:"threads"`

	// VersionInfo Version information for various components of the Thunderstorm service.
	VersionInfo ThunderstormVersionInfo `json:"version_info"`
}

// ThunderstormStatus Live information about the running THOR instance
type ThunderstormStatus struct {
	// AvgScanTimeMilliseconds Average time in milliseconds to scan a sample
	AvgScanTimeMilliseconds int64 `json:"avg_scan_time_milliseconds"`

	// AvgWaitTimeMilliseconds Average wait time in milliseconds before processing
	AvgWaitTimeMilliseconds int64 `json:"avg_wait_time_milliseconds"`

	// QueuedAsyncRequests Number of asynchronous requests currently in queue
	QueuedAsyncRequests int64 `json:"queued_async_requests"`

	// ScannedSamples Total number of samples that have been scanned
	ScannedSamples int64 `json:"scanned_samples"`
}

// ThunderstormVersionInfo Version information for various components of the Thunderstorm service.
type ThunderstormVersionInfo struct {
	// Build Build timestamp of the THOR scanner.
	Build *string `json:"build,omitempty"`

	// Sigma Version identifier of the Sigma rules.
	Sigma *string `json:"sigma,omitempty"`

	// Signatures Version/timestamp of the signature database.
	Signatures *string `json:"signatures,omitempty"`

	// Thor Version of the THOR scanner engine.
	Thor *string `json:"thor,omitempty"`
}

// TimestampMap Map of timestamps to integer values
type TimestampMap map[string]int64

// AggregationPeriod defines model for AggregationPeriod.
type AggregationPeriod = int64

// HistoryLimit defines model for HistoryLimit.
type HistoryLimit = int64

// SampleSource defines model for SampleSource.
type SampleSource = string

// BadRequest Error with message
type BadRequest = Error

// InternalServerError Error with message
type InternalServerError = Error

// QueueHistory Map of timestamps to integer values
type QueueHistory = TimestampMap

// SampleHistory Map of timestamps to integer values
type SampleHistory = TimestampMap

// CheckParams defines parameters for Check.
type CheckParams struct {
	// Source Specify source for the THOR log
	Source *SampleSource `form:"source,omitempty" json:"source,omitempty"`
}

// CheckAsyncParams defines parameters for CheckAsync.
type CheckAsyncParams struct {
	// Source Specify source for the THOR log
	Source *SampleSource `form:"source,omitempty" json:"source,omitempty"`
}

// GetAsyncResultsParams defines parameters for GetAsyncResults.
type GetAsyncResultsParams struct {
	// Id Sample ID
	Id SampleId `form:"id" json:"id"`
}

// QueueHistoryParams defines parameters for QueueHistory.
type QueueHistoryParams struct {
	// Aggregate Aggregate this many minutes per value (default 1).
	Aggregate *AggregationPeriod `form:"aggregate,omitempty" json:"aggregate,omitempty"`

	// Limit Give a history for the last this many minutes (default infinite).
	Limit *HistoryLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// SampleHistoryParams defines parameters for SampleHistory.
type SampleHistoryParams struct {
	// Aggregate Aggregate this many minutes per value (default 1).
	Aggregate *AggregationPeriod `form:"aggregate,omitempty" json:"aggregate,omitempty"`

	// Limit Give a history for the last this many minutes (default infinite).
	Limit *HistoryLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CheckMultipartRequestBody defines body for Check for multipart/form-data ContentType.
type CheckMultipartRequestBody = FileObject

// CheckAsyncMultipartRequestBody defines body for CheckAsync for multipart/form-data ContentType.
type CheckAsyncMultipartRequestBody = FileObject

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check a file with THOR
	// (POST /check)
	Check(w http.ResponseWriter, r *http.Request, params CheckParams)
	// Check a file with THOR asynchronously
	// (POST /checkAsync)
	CheckAsync(w http.ResponseWriter, r *http.Request, params CheckAsyncParams)
	// Retrieve the results of an asynchronous file check
	// (GET /getAsyncResults)
	GetAsyncResults(w http.ResponseWriter, r *http.Request, params GetAsyncResultsParams)
	// Receive static information about the running THOR instance
	// (GET /info)
	Info(w http.ResponseWriter, r *http.Request)
	// Retrieve a history of how many asynchronous requests were queued
	// (GET /queueHistory)
	QueueHistory(w http.ResponseWriter, r *http.Request, params QueueHistoryParams)
	// Retrieve a history of how many samples were scanned
	// (GET /sampleHistory)
	SampleHistory(w http.ResponseWriter, r *http.Request, params SampleHistoryParams)
	// Receive live information about the running THOR instance
	// (GET /status)
	Status(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Check operation middleware
func (siw *ServerInterfaceWrapper) Check(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckParams

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameter("form", true, false, "source", r.URL.Query(), &params.Source)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Check(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckAsync operation middleware
func (siw *ServerInterfaceWrapper) CheckAsync(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckAsyncParams

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameter("form", true, false, "source", r.URL.Query(), &params.Source)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckAsync(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsyncResults operation middleware
func (siw *ServerInterfaceWrapper) GetAsyncResults(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAsyncResultsParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsyncResults(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Info operation middleware
func (siw *ServerInterfaceWrapper) Info(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Info(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueueHistory operation middleware
func (siw *ServerInterfaceWrapper) QueueHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params QueueHistoryParams

	// ------------- Optional query parameter "aggregate" -------------

	err = runtime.BindQueryParameter("form", true, false, "aggregate", r.URL.Query(), &params.Aggregate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "aggregate", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueueHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SampleHistory operation middleware
func (siw *ServerInterfaceWrapper) SampleHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SampleHistoryParams

	// ------------- Optional query parameter "aggregate" -------------

	err = runtime.BindQueryParameter("form", true, false, "aggregate", r.URL.Query(), &params.Aggregate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "aggregate", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SampleHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Status operation middleware
func (siw *ServerInterfaceWrapper) Status(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Status(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/check", wrapper.Check)
	m.HandleFunc("POST "+options.BaseURL+"/checkAsync", wrapper.CheckAsync)
	m.HandleFunc("GET "+options.BaseURL+"/getAsyncResults", wrapper.GetAsyncResults)
	m.HandleFunc("GET "+options.BaseURL+"/info", wrapper.Info)
	m.HandleFunc("GET "+options.BaseURL+"/queueHistory", wrapper.QueueHistory)
	m.HandleFunc("GET "+options.BaseURL+"/sampleHistory", wrapper.SampleHistory)
	m.HandleFunc("GET "+options.BaseURL+"/status", wrapper.Status)

	return m
}

type BadRequestJSONResponse Error

type InternalServerErrorJSONResponse Error

type QueueHistoryJSONResponse TimestampMap

type SampleHistoryJSONResponse TimestampMap

type CheckRequestObject struct {
	Params CheckParams
	Body   *multipart.Reader
}

type CheckResponseObject interface {
	VisitCheckResponse(w http.ResponseWriter) error
}

type Check200JSONResponse ThorReport

func (response Check200JSONResponse) VisitCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Check400JSONResponse struct{ BadRequestJSONResponse }

func (response Check400JSONResponse) VisitCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Check500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Check500JSONResponse) VisitCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CheckAsyncRequestObject struct {
	Params CheckAsyncParams
	Body   *multipart.Reader
}

type CheckAsyncResponseObject interface {
	VisitCheckAsyncResponse(w http.ResponseWriter) error
}

type CheckAsync200JSONResponse SampleIdObj

func (response CheckAsync200JSONResponse) VisitCheckAsyncResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CheckAsync400JSONResponse struct{ BadRequestJSONResponse }

func (response CheckAsync400JSONResponse) VisitCheckAsyncResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CheckAsync500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CheckAsync500JSONResponse) VisitCheckAsyncResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAsyncResultsRequestObject struct {
	Params GetAsyncResultsParams
}

type GetAsyncResultsResponseObject interface {
	VisitGetAsyncResultsResponse(w http.ResponseWriter) error
}

type GetAsyncResults200JSONResponse AsyncResult

func (response GetAsyncResults200JSONResponse) VisitGetAsyncResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAsyncResults400JSONResponse struct{ BadRequestJSONResponse }

func (response GetAsyncResults400JSONResponse) VisitGetAsyncResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAsyncResults500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAsyncResults500JSONResponse) VisitGetAsyncResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InfoRequestObject struct {
}

type InfoResponseObject interface {
	VisitInfoResponse(w http.ResponseWriter) error
}

type Info200JSONResponse ThunderstormInfo

func (response Info200JSONResponse) VisitInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Info500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Info500JSONResponse) VisitInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type QueueHistoryRequestObject struct {
	Params QueueHistoryParams
}

type QueueHistoryResponseObject interface {
	VisitQueueHistoryResponse(w http.ResponseWriter) error
}

type QueueHistory200JSONResponse struct{ QueueHistoryJSONResponse }

func (response QueueHistory200JSONResponse) VisitQueueHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type QueueHistory400JSONResponse struct{ BadRequestJSONResponse }

func (response QueueHistory400JSONResponse) VisitQueueHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SampleHistoryRequestObject struct {
	Params SampleHistoryParams
}

type SampleHistoryResponseObject interface {
	VisitSampleHistoryResponse(w http.ResponseWriter) error
}

type SampleHistory200JSONResponse struct{ SampleHistoryJSONResponse }

func (response SampleHistory200JSONResponse) VisitSampleHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SampleHistory400JSONResponse struct{ BadRequestJSONResponse }

func (response SampleHistory400JSONResponse) VisitSampleHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type StatusRequestObject struct {
}

type StatusResponseObject interface {
	VisitStatusResponse(w http.ResponseWriter) error
}

type Status200JSONResponse ThunderstormStatus

func (response Status200JSONResponse) VisitStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Check a file with THOR
	// (POST /check)
	Check(ctx context.Context, request CheckRequestObject) (CheckResponseObject, error)
	// Check a file with THOR asynchronously
	// (POST /checkAsync)
	CheckAsync(ctx context.Context, request CheckAsyncRequestObject) (CheckAsyncResponseObject, error)
	// Retrieve the results of an asynchronous file check
	// (GET /getAsyncResults)
	GetAsyncResults(ctx context.Context, request GetAsyncResultsRequestObject) (GetAsyncResultsResponseObject, error)
	// Receive static information about the running THOR instance
	// (GET /info)
	Info(ctx context.Context, request InfoRequestObject) (InfoResponseObject, error)
	// Retrieve a history of how many asynchronous requests were queued
	// (GET /queueHistory)
	QueueHistory(ctx context.Context, request QueueHistoryRequestObject) (QueueHistoryResponseObject, error)
	// Retrieve a history of how many samples were scanned
	// (GET /sampleHistory)
	SampleHistory(ctx context.Context, request SampleHistoryRequestObject) (SampleHistoryResponseObject, error)
	// Receive live information about the running THOR instance
	// (GET /status)
	Status(ctx context.Context, request StatusRequestObject) (StatusResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Check operation middleware
func (sh *strictHandler) Check(w http.ResponseWriter, r *http.Request, params CheckParams) {
	var request CheckRequestObject

	request.Params = params

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Check(ctx, request.(CheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Check")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CheckResponseObject); ok {
		if err := validResponse.VisitCheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CheckAsync operation middleware
func (sh *strictHandler) CheckAsync(w http.ResponseWriter, r *http.Request, params CheckAsyncParams) {
	var request CheckAsyncRequestObject

	request.Params = params

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CheckAsync(ctx, request.(CheckAsyncRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckAsync")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CheckAsyncResponseObject); ok {
		if err := validResponse.VisitCheckAsyncResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAsyncResults operation middleware
func (sh *strictHandler) GetAsyncResults(w http.ResponseWriter, r *http.Request, params GetAsyncResultsParams) {
	var request GetAsyncResultsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAsyncResults(ctx, request.(GetAsyncResultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAsyncResults")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAsyncResultsResponseObject); ok {
		if err := validResponse.VisitGetAsyncResultsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Info operation middleware
func (sh *strictHandler) Info(w http.ResponseWriter, r *http.Request) {
	var request InfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Info(ctx, request.(InfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Info")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InfoResponseObject); ok {
		if err := validResponse.VisitInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// QueueHistory operation middleware
func (sh *strictHandler) QueueHistory(w http.ResponseWriter, r *http.Request, params QueueHistoryParams) {
	var request QueueHistoryRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.QueueHistory(ctx, request.(QueueHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "QueueHistory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(QueueHistoryResponseObject); ok {
		if err := validResponse.VisitQueueHistoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SampleHistory operation middleware
func (sh *strictHandler) SampleHistory(w http.ResponseWriter, r *http.Request, params SampleHistoryParams) {
	var request SampleHistoryRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SampleHistory(ctx, request.(SampleHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SampleHistory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SampleHistoryResponseObject); ok {
		if err := validResponse.VisitSampleHistoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Status operation middleware
func (sh *strictHandler) Status(w http.ResponseWriter, r *http.Request) {
	var request StatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Status(ctx, request.(StatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Status")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StatusResponseObject); ok {
		if err := validResponse.VisitStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
