//go:build go1.22

// Package thunderstormmock provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package thunderstormmock

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AsyncResult Result object for asynchronous scan operations
type AsyncResult struct {
	// Result THOR Report containing findings
	Result *ThorReport `json:"result,omitempty"`

	// Status Current status of the scan
	Status string `json:"status"`
}

// Error Error with message
type Error struct {
	// Message Error message describing the problem
	Message string `json:"message"`
}

// FileObject Wrapped file
type FileObject struct {
	// File File to be checked
	File openapi_types.File `json:"file"`
}

// SampleId Sample ID returned for an asynchronous scan request
type SampleId = int64

// SampleIdObj Object containing the Sample ID returned for an asynchronous scan request
type SampleIdObj struct {
	// Id Sample ID returned for an asynchronous scan request
	Id int64 `json:"id"`
}

// ThorFinding THOR Finding
type ThorFinding map[string]interface{}

// ThorReport THOR Report containing findings
type ThorReport = []ThorFinding

// ThunderstormInfo Information about the Thunderstorm service instance, including version details, configuration, and license information.
type ThunderstormInfo struct {
	// Arguments Command-line arguments used to start the underlying THOR instance.
	Arguments []string `json:"arguments"`

	// LicenseExpiration Expiration date and time of the license in ISO 8601 format.
	LicenseExpiration time.Time `json:"license_expiration"`

	// LicenseOwner Name of the license owner.
	LicenseOwner string `json:"license_owner"`

	// ScanSpeedLimitation Scan speed limitation in bytes per second. A value of 0 indicates no limitation.
	ScanSpeedLimitation int64 `json:"scan_speed_limitation"`

	// Threads Number of threads used for scanning.
	Threads int64 `json:"threads"`

	// VersionInfo Version information for various components of the Thunderstorm service.
	VersionInfo ThunderstormVersionInfo `json:"version_info"`
}

// ThunderstormStatus Live information about the running THOR instance
type ThunderstormStatus struct {
	// AvgScanTimeMilliseconds Average time in milliseconds to scan a sample
	AvgScanTimeMilliseconds int64 `json:"avg_scan_time_milliseconds"`

	// AvgWaitTimeMilliseconds Average wait time in milliseconds before processing
	AvgWaitTimeMilliseconds int64 `json:"avg_wait_time_milliseconds"`

	// QueuedAsyncRequests Number of asynchronous requests currently in queue
	QueuedAsyncRequests int64 `json:"queued_async_requests"`

	// ScannedSamples Total number of samples that have been scanned
	ScannedSamples int64 `json:"scanned_samples"`
}

// ThunderstormVersionInfo Version information for various components of the Thunderstorm service.
type ThunderstormVersionInfo struct {
	// Build Build timestamp of the THOR scanner.
	Build *string `json:"build,omitempty"`

	// Sigma Version identifier of the Sigma rules.
	Sigma *string `json:"sigma,omitempty"`

	// Signatures Version/timestamp of the signature database.
	Signatures *string `json:"signatures,omitempty"`

	// Thor Version of the THOR scanner engine.
	Thor *string `json:"thor,omitempty"`
}

// TimestampMap Map of timestamps to integer values
type TimestampMap map[string]int64

// CheckParams defines parameters for Check.
type CheckParams struct {
	// Source Specify source for the THOR log
	Source *string `form:"source,omitempty" json:"source,omitempty"`
}

// CheckAsyncParams defines parameters for CheckAsync.
type CheckAsyncParams struct {
	// Source Specify source for the THOR log
	Source *string `form:"source,omitempty" json:"source,omitempty"`
}

// GetAsyncResultsParams defines parameters for GetAsyncResults.
type GetAsyncResultsParams struct {
	// Id Sample ID
	Id SampleId `form:"id" json:"id"`
}

// QueueHistoryParams defines parameters for QueueHistory.
type QueueHistoryParams struct {
	// Aggregate Aggregate this many minutes per value (default 1).
	Aggregate *int64 `form:"aggregate,omitempty" json:"aggregate,omitempty"`

	// Limit Give a history for the last this many minutes (default infinite).
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// SampleHistoryParams defines parameters for SampleHistory.
type SampleHistoryParams struct {
	// Aggregate Aggregate this many minutes per value (default 1).
	Aggregate *int64 `form:"aggregate,omitempty" json:"aggregate,omitempty"`

	// Limit Give a history for the last this many minutes (default infinite).
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// CheckMultipartRequestBody defines body for Check for multipart/form-data ContentType.
type CheckMultipartRequestBody = FileObject

// CheckAsyncMultipartRequestBody defines body for CheckAsync for multipart/form-data ContentType.
type CheckAsyncMultipartRequestBody = FileObject

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check a file with THOR
	// (POST /check)
	Check(w http.ResponseWriter, r *http.Request, params CheckParams)
	// Check a file with THOR asynchronously
	// (POST /checkAsync)
	CheckAsync(w http.ResponseWriter, r *http.Request, params CheckAsyncParams)
	// Retrieve the results of an asynchronous file check
	// (GET /getAsyncResults)
	GetAsyncResults(w http.ResponseWriter, r *http.Request, params GetAsyncResultsParams)
	// Receive static information about the running THOR instance
	// (GET /info)
	Info(w http.ResponseWriter, r *http.Request)
	// Retrieve a history of how many asynchronous requests were queued
	// (GET /queueHistory)
	QueueHistory(w http.ResponseWriter, r *http.Request, params QueueHistoryParams)
	// Retrieve a history of how many samples were scanned
	// (GET /sampleHistory)
	SampleHistory(w http.ResponseWriter, r *http.Request, params SampleHistoryParams)
	// Receive live information about the running THOR instance
	// (GET /status)
	Status(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Check operation middleware
func (siw *ServerInterfaceWrapper) Check(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckParams

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameter("form", true, false, "source", r.URL.Query(), &params.Source)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Check(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckAsync operation middleware
func (siw *ServerInterfaceWrapper) CheckAsync(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckAsyncParams

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameter("form", true, false, "source", r.URL.Query(), &params.Source)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckAsync(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsyncResults operation middleware
func (siw *ServerInterfaceWrapper) GetAsyncResults(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAsyncResultsParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsyncResults(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Info operation middleware
func (siw *ServerInterfaceWrapper) Info(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Info(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueueHistory operation middleware
func (siw *ServerInterfaceWrapper) QueueHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params QueueHistoryParams

	// ------------- Optional query parameter "aggregate" -------------

	err = runtime.BindQueryParameter("form", true, false, "aggregate", r.URL.Query(), &params.Aggregate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "aggregate", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueueHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SampleHistory operation middleware
func (siw *ServerInterfaceWrapper) SampleHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SampleHistoryParams

	// ------------- Optional query parameter "aggregate" -------------

	err = runtime.BindQueryParameter("form", true, false, "aggregate", r.URL.Query(), &params.Aggregate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "aggregate", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SampleHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Status operation middleware
func (siw *ServerInterfaceWrapper) Status(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Status(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/check", wrapper.Check)
	m.HandleFunc("POST "+options.BaseURL+"/checkAsync", wrapper.CheckAsync)
	m.HandleFunc("GET "+options.BaseURL+"/getAsyncResults", wrapper.GetAsyncResults)
	m.HandleFunc("GET "+options.BaseURL+"/info", wrapper.Info)
	m.HandleFunc("GET "+options.BaseURL+"/queueHistory", wrapper.QueueHistory)
	m.HandleFunc("GET "+options.BaseURL+"/sampleHistory", wrapper.SampleHistory)
	m.HandleFunc("GET "+options.BaseURL+"/status", wrapper.Status)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabZPbNpL+K1jcpS7xURL4Kkpb92HiOOtZxx7vzHhzWZ9LB5FNCRkSZABQHq1r/vsV",
	"AFKiRGpe7MterjYulz1DAt2N7qcbDxr8hJOyqEoOXEk8/4QF/FKDVN+WKQPz4HuWw7sqL2mqf0tKroAr",
	"/WNR54pVVKhJVopilFJF9WOZrKEwP/2rgAzP8b9M9hom9q2caKkXy58hUfju7s7BKchEsEqxkuM5ft2K",
	"Rlo00qKR1kwZZ3yFKMpYDtgxxjIBKZ4rUYOW08jX6s/klieXIOvcmHuowT5HpTFBa0FUD1+Lkpe1RDKh",
	"HJUVCKrHS+xguKVFlYN1kZX5vnHHrcJzXue5g/NytdiAkFbHxh+TMcEOLkBKugI8x1e1rFjCtAq9BJSV",
	"NU/NCOu8dSkVp4Ue6npTPX3sYgfnsIEcz/GPVGgH6AllWmtr8Mvr67dXIDYgsF495QuWakWjX9hfz8tp",
	"Vng/3YwC7GDFjFiPeNGIuCN3du1GcxLPvek4JrMg9mdh+O/EnROC77RnqSz5IilrHWy3fSDNqguqkrX2",
	"+vtP2IYd/9uH//jDH95/+OMddnDGINc2TFqwOLjMMgkKz/04Cu8+OFiyFaeqFsafKVWNZeGI+CNvdk3I",
	"3Pz9Gz5GxnegIFESlcuslglVkKI/0w29MkNQUqYaFjeMa/0/nV2eocvaIKUUbMW0AMYVCE5zjZ46h0Xj",
	"7Ytvv3939dy4sNRWRaGDFV3p9dp3+INGV10UVGxb2VoA2s1U20pLso7CZpVW1nSmZ1qwH6YQ5FDYxNt7",
	"ckMFWpDbjtO8qa+l5cBXao3noR/NdtpkRYUEkyE6bHDLpBaHt2BBq4A3aDSBEVItlltlM5vKhDEdp2fo",
	"vYCPgilYYAev4VZHI/MooRBToKn+d0k8Qmi4nHpROJ1OvWg2DaIwzLTWNZVrK7JIQzzHWZZMgzSkWeJ5",
	"qZu5yTQOs1nshkGSTJdUx0OuqYvneBYRnwYxiUIvDqdxFEdpEmbEW8YkTKIgcIOln8zcpZ3hhRGe45S6",
	"qedP42xJkywOUjJL3ZjOghSy2E9Sf5klJIJ4BtPAmy2pn0I4TdJZRAmQgMZTbXFBVyxZrPXaBJ7jd29e",
	"vbn48Q12cEW1i3E0JWQaxks3yCCmibtcJstl5qdR6EWun8Z6JIiCSWnKQ5P+kv0djuJjCtXd7tfrlxeX",
	"KGM81VlsIKKoqnXArkx5QZTTfCuZRLpm5qDM5EroUqSagix2Je2+Anu9LsUlVKVQWkKr5rgMPq+FAK6Q",
	"fY/KDKk1mOrXLXntsHyLlqALsB7AId2DXiphVnTXrcnvW7UfduPKpuQ7+IUQpegbZB6jj0ytUVs1D2rv",
	"vpS2P/X8sxsyLLt5jey7pV6OXnMlymUOxYNLaqUPramzqfWU/yhoVUHa7lyHJpuHvSlaHFIlWgJK1pDc",
	"GIfrDZEqPMdLxnUpesheI3rIWAu487Svt4Hi+XdIgKoF11brDZIP7JENXegGyfX8IOwYyriKgr2dugCv",
	"QHRNuFj+3LfCOrK77eswfaFtn7DeHY2FPdyw/ztXHMWMpYMR0yn9fVM7dPlOU6bNpPnbzjo0ETreNE3V",
	"aWeeENzUip4HzFz7shuLpoYdMKPP4EOvaf4FdOgsB6EeR4Zu/rIJty/P3728GXkDZCi6dv25H879YOy6",
	"ru+7U+8UF/LiB8nQV8/ks2fPL1989+LN9fnZD8+e3U+KZm4cxOTO6c5H6K32m1So+TNHX5H4Fo3QV7X+",
	"Rz4kckbC6FDks2ffXbw+O3/z6sVPD1oUkiiO7yFq/oiEI9d7BFG7KgtQawu8x/IyyEAATzSk8HnzHF2C",
	"BCqStU6NLnPTChZa2uKNfrBjXXGHwb34zxfYwS9fXf9wRONkWQDacbk+iXMG43tTr/NFscglTeuiWqxA",
	"vZMg5BlPr2jxCrboj+imzvUQASsmldguLmF1UQF/BdsXt+jq7DU6SwyeJPqa3OrIfnN/RFyXkDDogqRv",
	"xPOyqGoFQtuxlTeNHcejmlevLh5QSGazKbkHA240It6IhE/BACrV2uTm5yBBS0H7J0cwOONG9iASyB4J",
	"1y4JZwtC3CMgNNNPwGDP5WfBU7j8f9WE+PDfPBHbSo3TPO84OA4j1yVdYu/6oefOvM/g9mO4hdP8/vXf",
	"dqxes/IZIYT4xP4J7H9ZlmX6/2Vsfx9i9VM3iuOZF838dDp1I88j6SyOYz/LsjQO4mTP6gOPJulsGYYB",
	"uEkc+HSWxa4/I563DCOSAllmQRzFXpfVRxEJoiAJpn4STKdxkMaxR1IfvChOSOr63pQmnpcAgYhM08QP",
	"IQ7jyIuT0M9INMjqbdY3jF5nut5jGledZO/HQXiIwDMFhXwMGW/3370sKgTd2v235ikIqUpRnPOs7O/C",
	"+qnmEKzkiC7LWhky1J2HJIgNSwAxLhXlCTiI8SSvtU7U7MEoBUVZLh29k2dsVdv2hoMoT1HOEuBSz9+p",
	"Gh9SJypWdQtxPBpZGdjBk7JSEw63SpR8ojo2TeyQSVJLVRYjtS7FeFvkOnUbbQu4rZi1YrcdT0ckPigq",
	"7djyIzdxpWnBeLvBywogXeSsYKoRo7N9LYCmEs/dyMHN4hes8eyyZqbotZs/mV6TYE68ue9qbZKtCp27",
	"wvQjXM/wg3i0itIwdqdRALhTEWUjZ0LcieuN3IiEoWY4eqmatJBxPCaG3x1yzY4re0eysigoT0c544B2",
	"41AtIdWHAamosNE3fs63Or4GlW3gD6L2xYHa4fvomNFH8VBIe0ew3Ttd1sAAT3Ox9uS5ByE6v7pAcURc",
	"ZOF4sKpTSNkRbS18ZEie0zf8CE/HNurN49geM/TQhBaFPfEnYNk7WugzgxmG9sP0wk39RhUIJCEpeTpG",
	"Z2hD89oYRZAuIwnVQ3jZmXlgHHnU8WuXJT0P1MUShPWBGWLRp08+5uTP+OpAnc6yR+g7TsT7K+YenX+1",
	"80xlPD4q7RNpEIDHwT4Vnb0zjswcPoftbbs60Vj5gW0OSmmnaovaePAwaY8q7Wa1MIZqCC8KlufMYkHi",
	"uec65v1HytTQe+LgX2qoIV2YI+qiOZbaN03jZiGNKl0g4yiOfNI/Dd9nwvFizzYg6ApsJjOOuqNNzdJQ",
	"p8gq7a5Ur+URwLlvuads0eOHDVpCVgrT8ElASnsyeWLmnHDw6Tw66Ba0E1Cya6sxjozMp5vSi2jvAF8q",
	"miO+M6UZiNSaKrSmG0BLAN5p6e3TusHG0xsY94Dn3mie8mx/mQ/lZbdm9FzSvDzIT13cNlSYXsS+HrX7",
	"wBDTGvfaeA2zOFb3rX5ssCgVLaqdTJ3/dl1iaHfrMZP+TmOpysnlpcAVy1hbygFd6QnmjCMPNd5HdobU",
	"7tjPCd2T3mp3k8x5Zkkl9NfcY1E9yrEe6hm36x3wKwK+YvxIVcPKhjqnfUy163hNq9NNt0+PydSjK05q",
	"XdPKN4WyGW23+6NbxxYUnotINA9CUyC6D6dzQvB85kbh8XM3xPNgRjz/+IVP8Dxyo7g3Q4sPg5nv9X2i",
	"3cQG0+p6zSQ6e3uOaJ6XHyXalrWp/sBt29ss0USn3RPUGgrDAStRblgK8ilb5tj08VS+O5YdJOnZ2/P9",
	"Xq6DbnqPdw4uK+C00udif0zGQXNCNEGcmDa7/qkq5UAv9Ll+3dw+2zsKrRcbmZZwnKftMCNX0AIUiKYn",
	"cEj/KkhYtkWyrEUCpvzswJuXdk+q8jKFtqVreiO/1GB6/k3Tw07GTufSvZ+tamtcpP1qTqz7G/7tKRZ2",
	"8BHApPMFgKnzsiq5tLD3NOQO2iC0qnLNT3UR+Fla4vu4TwK6N1b9TwIuTf9dIopyJpVOnV0L+s7Bwf+i",
	"HfZmasCEc76hOUvRPq5oxTbAtQHhP8KAd5zWugSyv0NqytW+f3USmm3jy9zpfdCTLMrN1xFPhfoBj8m3",
	"w8i3kn+H/xOj3r0Muxf/Ba2Ob8Vke031ey48AbsDqbEC1flsyMR4BYOfDynBYAN2d7KDDc8/uhg0Jph8",
	"G/eS5U9Huh7KmF2MH5UbLO19H+U8EYkn0udXwn/3c6178f/nq4s3Nqza+cnhFwyUpw5iGWrsWObgdGP0",
	"e358Fng7ydI60uZLSwRPJEkCbAMmNCx5KrU7TBZzkPtVycdRC37oq0RaWdxZeq5ZbGt9wzMdJKiCTlfO",
	"QePx+LcR88+NRSf2tiNmAm/O6S+Z9tf24SpJ0doO1TBblx9RQfn2RFPkIwiwzZC0h4K/dLU+UC/PVisB",
	"Kx0Opc8lRmPBeN02V21L9esUMlrnCrnfjB9XWGkr94B3PKZTc1BKnWN7/8QOHNUyopxKNbCCnd2MZ4wz",
	"BY8132Dzy0z/NXeBg/P2AMTPbPnfpSLQZG3bfIX9vkqVxm0GQMjerKKvQSpWUAXpNygTZdFxrJkJXEtv",
	"J1P7ePwb2CuGy/bnZ9NAIlvq+IWZ3PYUjbamVdev4VcHqn5P33/C9D1icQ+mcQusBlOPz97/Z8k7lEAn",
	"8nV34XQv58qfeP80kK1W0T+IczXaHse6bO9QQ83ZIaPxoLO/+JEN+RrkQfnT7+eOg6Hlmm8Nh8rXD2VC",
	"856IWuR4jtdKVfPJJNdD1qVU85jEZEIrNtm4Jj0bTb3Lc55WJeNq7wPbVe22e9rOiD7S9ovUgQTRQrJ7",
	"BDj+qlXuZe6PUI8T+zTvtsdWw70/3P1PAAAA//8WyoUqlzQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
