//go:build go1.22

// Package thunderstormmock provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package thunderstormmock

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AsyncResult Result object for asynchronous scan operations
type AsyncResult struct {
	// Result THOR Report containing findings
	Result *ThorReport `json:"result,omitempty"`

	// Status Current status of the scan
	Status string `json:"status"`
}

// Error Error with message
type Error struct {
	// Message Error message describing the problem
	Message string `json:"message"`
}

// FileObject Wrapped file
type FileObject struct {
	// File File to be checked
	File openapi_types.File `json:"file"`
}

// SampleId Sample ID returned for an asynchronous scan request
type SampleId = int64

// SampleIdObj Object containing the Sample ID returned for an asynchronous scan request
type SampleIdObj struct {
	// Id Sample ID returned for an asynchronous scan request
	Id SampleId `json:"id"`
}

// ThorFinding THOR Finding
type ThorFinding map[string]interface{}

// ThorReport THOR Report containing findings
type ThorReport = []ThorFinding

// ThunderstormInfo Information about the Thunderstorm service instance, including version details, configuration, and license information.
type ThunderstormInfo struct {
	// Arguments Command-line arguments used to start the underlying THOR instance.
	Arguments []string `json:"arguments"`

	// LicenseExpiration Expiration date and time of the license in ISO 8601 format.
	LicenseExpiration time.Time `json:"license_expiration"`

	// LicenseOwner Name of the license owner.
	LicenseOwner string `json:"license_owner"`

	// ScanSpeedLimitation Scan speed limitation in bytes per second. A value of 0 indicates no limitation.
	ScanSpeedLimitation int64 `json:"scan_speed_limitation"`

	// Threads Number of threads used for scanning.
	Threads int64 `json:"threads"`

	// VersionInfo Version information for various components of the Thunderstorm service.
	VersionInfo ThunderstormVersionInfo `json:"version_info"`
}

// ThunderstormStatus Live information about the running THOR instance
type ThunderstormStatus struct {
	// AvgScanTimeMilliseconds Average time in milliseconds to scan a sample
	AvgScanTimeMilliseconds int64 `json:"avg_scan_time_milliseconds"`

	// AvgWaitTimeMilliseconds Average wait time in milliseconds before processing
	AvgWaitTimeMilliseconds int64 `json:"avg_wait_time_milliseconds"`

	// QueuedAsyncRequests Number of asynchronous requests currently in queue
	QueuedAsyncRequests int64 `json:"queued_async_requests"`

	// ScannedSamples Total number of samples that have been scanned
	ScannedSamples int64 `json:"scanned_samples"`
}

// ThunderstormVersionInfo Version information for various components of the Thunderstorm service.
type ThunderstormVersionInfo struct {
	// Build Build timestamp of the THOR scanner.
	Build *string `json:"build,omitempty"`

	// Sigma Version identifier of the Sigma rules.
	Sigma *string `json:"sigma,omitempty"`

	// Signatures Version/timestamp of the signature database.
	Signatures *string `json:"signatures,omitempty"`

	// Thor Version of the THOR scanner engine.
	Thor *string `json:"thor,omitempty"`
}

// TimestampMap Map of timestamps to integer values
type TimestampMap map[string]int64

// AggregationPeriod defines model for AggregationPeriod.
type AggregationPeriod = int64

// HistoryLimit defines model for HistoryLimit.
type HistoryLimit = int64

// SampleSource defines model for SampleSource.
type SampleSource = string

// BadRequest Error with message
type BadRequest = Error

// InternalServerError Error with message
type InternalServerError = Error

// QueueHistory Map of timestamps to integer values
type QueueHistory = TimestampMap

// SampleHistory Map of timestamps to integer values
type SampleHistory = TimestampMap

// CheckParams defines parameters for Check.
type CheckParams struct {
	// Source Specify source for the THOR log
	Source *SampleSource `form:"source,omitempty" json:"source,omitempty"`
}

// CheckAsyncParams defines parameters for CheckAsync.
type CheckAsyncParams struct {
	// Source Specify source for the THOR log
	Source *SampleSource `form:"source,omitempty" json:"source,omitempty"`
}

// GetAsyncResultsParams defines parameters for GetAsyncResults.
type GetAsyncResultsParams struct {
	// Id Sample ID
	Id SampleId `form:"id" json:"id"`
}

// QueueHistoryParams defines parameters for QueueHistory.
type QueueHistoryParams struct {
	// Aggregate Aggregate this many minutes per value (default 1).
	Aggregate *AggregationPeriod `form:"aggregate,omitempty" json:"aggregate,omitempty"`

	// Limit Give a history for the last this many minutes (default infinite).
	Limit *HistoryLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// SampleHistoryParams defines parameters for SampleHistory.
type SampleHistoryParams struct {
	// Aggregate Aggregate this many minutes per value (default 1).
	Aggregate *AggregationPeriod `form:"aggregate,omitempty" json:"aggregate,omitempty"`

	// Limit Give a history for the last this many minutes (default infinite).
	Limit *HistoryLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CheckMultipartRequestBody defines body for Check for multipart/form-data ContentType.
type CheckMultipartRequestBody = FileObject

// CheckAsyncMultipartRequestBody defines body for CheckAsync for multipart/form-data ContentType.
type CheckAsyncMultipartRequestBody = FileObject

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check a file with THOR
	// (POST /check)
	Check(w http.ResponseWriter, r *http.Request, params CheckParams)
	// Check a file with THOR asynchronously
	// (POST /checkAsync)
	CheckAsync(w http.ResponseWriter, r *http.Request, params CheckAsyncParams)
	// Retrieve the results of an asynchronous file check
	// (GET /getAsyncResults)
	GetAsyncResults(w http.ResponseWriter, r *http.Request, params GetAsyncResultsParams)
	// Receive static information about the running THOR instance
	// (GET /info)
	Info(w http.ResponseWriter, r *http.Request)
	// Retrieve a history of how many asynchronous requests were queued
	// (GET /queueHistory)
	QueueHistory(w http.ResponseWriter, r *http.Request, params QueueHistoryParams)
	// Retrieve a history of how many samples were scanned
	// (GET /sampleHistory)
	SampleHistory(w http.ResponseWriter, r *http.Request, params SampleHistoryParams)
	// Receive live information about the running THOR instance
	// (GET /status)
	Status(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Check operation middleware
func (siw *ServerInterfaceWrapper) Check(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckParams

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameter("form", true, false, "source", r.URL.Query(), &params.Source)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Check(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckAsync operation middleware
func (siw *ServerInterfaceWrapper) CheckAsync(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckAsyncParams

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameter("form", true, false, "source", r.URL.Query(), &params.Source)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckAsync(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsyncResults operation middleware
func (siw *ServerInterfaceWrapper) GetAsyncResults(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAsyncResultsParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsyncResults(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Info operation middleware
func (siw *ServerInterfaceWrapper) Info(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Info(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueueHistory operation middleware
func (siw *ServerInterfaceWrapper) QueueHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params QueueHistoryParams

	// ------------- Optional query parameter "aggregate" -------------

	err = runtime.BindQueryParameter("form", true, false, "aggregate", r.URL.Query(), &params.Aggregate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "aggregate", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueueHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SampleHistory operation middleware
func (siw *ServerInterfaceWrapper) SampleHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SampleHistoryParams

	// ------------- Optional query parameter "aggregate" -------------

	err = runtime.BindQueryParameter("form", true, false, "aggregate", r.URL.Query(), &params.Aggregate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "aggregate", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SampleHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Status operation middleware
func (siw *ServerInterfaceWrapper) Status(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Status(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/check", wrapper.Check)
	m.HandleFunc("POST "+options.BaseURL+"/checkAsync", wrapper.CheckAsync)
	m.HandleFunc("GET "+options.BaseURL+"/getAsyncResults", wrapper.GetAsyncResults)
	m.HandleFunc("GET "+options.BaseURL+"/info", wrapper.Info)
	m.HandleFunc("GET "+options.BaseURL+"/queueHistory", wrapper.QueueHistory)
	m.HandleFunc("GET "+options.BaseURL+"/sampleHistory", wrapper.SampleHistory)
	m.HandleFunc("GET "+options.BaseURL+"/status", wrapper.Status)

	return m
}
